### ISSUE TITLE
Threat intelligence feeds blocking tropicalspicegarden.com

### ISSUE THREAD

**Issue by ghost** [nextdns/metadata#1158]
`tropicalspicegarden.com` is a legit website for a garden in Malaysia.
It is found in `phishing.army/download/phishing_army_blocklist.txt`

**Comment by botthebestplayerintheworld** [comment]
![image](https://user-images.githubusercontent.com/96731476/206968759-4d982e09-527f-4a08-8e65-7f9e200c1898.png)

**Comment by botthebestplayerintheworld** [comment]
![image](https://user-images.githubusercontent.com/96731476/206968842-013b3759-4328-44f2-81b6-aa8d62d34a08.png)

**Comment by romaincointepas** [comment]
It was not there yesterday, it made its way back. @drego85 can you check?

**Comment by drego85** [comment]
The source of this false positive is [PhishTank](https://www.phishtank.com/phish_detail.php?phish_id=6072208). They report, still today, that the phishing site is active.

The domain has indeed hosted a phishing site in the past, it was probably compromised. [An Example](https://urlscan.io/result/37ea775a-71f6-49c0-ba64-6824715f3a30/).

I ask PhishTank to review the report and report that the website is no longer phishing.

**Comment by drego85** [comment]
A further detail, [VirusTotal](https://www.virustotal.com/gui/url/a676ff840587e2cda79bf6cf397d42b0cbc29335b2ed999f50799a59eb87c3e9/detection) always reports that the domain continues to be malicious.

**Comment by drego85** [comment]
PhishTank has updated the status (Submission #6072208 is currently offline)

Probably at the next generation of the list (it is created every 6h) the domain will be removed.

**Comment by drego85** [comment]
PhisTank has removed the domain, it still remains in [Phishing.Database ](https://raw.githubusercontent.com/mitchellkrogza/Phishing.Database/master/phishing-links-NEW-today.txt)of @mitchellkrogza.

I hope it will also be eliminated from this additional source in the next few hours.

**Comment by ghost** [comment]
It's still there

**Comment by hagezi** [comment]
@drego85 It is currently blocked by Phishing.Army, which is why it ended up on my lists again.
```
Domain:
 - tropicalspicegarden.com OK

Malware/Phishing/Scam:
 - Malicous?       POSSIBLE (1)

 - Threat?
   HaGeZi.TIF.LT   YES
   HaGeZi.TIF      YES
   HaGeZi.TIF.RAW  YES
   Quad9           NO
   OpenDNS         NO
   ThreatFox       NO
   URLhaus         NO
   ThreatView      NO
   KADHosts        NO

 - Phishing?
   Phishing.Army   YES
   PT/OP/PH        NO
   CERT.PL         NO
   Phishing.DB     YES

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         -/-

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    BLOCKED
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  BLOCKED
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - AhaDNS          OK
 - CONTROLD        BLOCKED
 - DNSforge.de     BLOCKED
 - EasyList        OK
 - HaGeZi.LIGHT    BLOCKED
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PERSONAL BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          BLOCKED
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      BLOCKED
 - OISD            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=tropicalspicegarden.com
 - VirusTotal      https://www.virustotal.com/en/domain/tropicalspicegarden.com/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/tropicalspicegarden.com
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Ftropicalspicegarden.com
 - FortiGuard      https://www.fortiguard.com/webfilter?q=tropicalspicegarden.com
 - Kaspersky       https://opentip.kaspersky.com/tropicalspicegarden.com?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=tropicalspicegarden.com
 - Norton          https://safeweb.norton.com/report/show?url=tropicalspicegarden.com
 - OpenDNS         https://domain.opendns.com/tropicalspicegarden.com
 - URLVoid         https://www.urlvoid.com/scan/tropicalspicegarden.com/
 - Yandex          https://yandex.com/safety/?l10n=en&url=tropicalspicegarden.com
```
